name: Bug Report 🐛
description: Report something that's not working the way it's (probably) intended to
title: '[BUG] <title>'
labels: ['🐛 Bug']
assignees:
  - rotkiW285

body:
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: Please describe exactly what is not working.
    validations:
      required: true

  - type: textarea
    id: bug_steps
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the bug
      placeholder: When doing ABC then DEF, I expect to see XYZ, but I actually see ZYX
    validations:
      required: true


  - type: dropdown
    id: browser
    attributes:
      label: On which version did you find the bug?
      multiple: false
      options:
        - Desktop
        - Mobile
        - Both

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is it to fix this issue?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
